// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA-_NhJAdz2CeGN4y96xMzc7Vw8c1UAqI',
    appId: '1:691260257997:web:53f8d078ee027d64819b84',
    messagingSenderId: '691260257997',
    projectId: 'dcme-app',
    authDomain: 'dcme-app.firebaseapp.com',
    storageBucket: 'dcme-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVb5EAJ8v4K2WXnOPQ9F7XeHIcUAF5pTw',
    appId: '1:691260257997:android:9925451cf36b6f57819b84',
    messagingSenderId: '691260257997',
    projectId: 'dcme-app',
    storageBucket: 'dcme-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Y_pGk_ZesNsTlF280BfituF2NJ3G6yg',
    appId: '1:691260257997:ios:f2000e755d97fd1f819b84',
    messagingSenderId: '691260257997',
    projectId: 'dcme-app',
    storageBucket: 'dcme-app.appspot.com',
    iosClientId: '691260257997-cge8c614vfohamdnb75t1p63ehi0k6hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.dcmeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Y_pGk_ZesNsTlF280BfituF2NJ3G6yg',
    appId: '1:691260257997:ios:f2000e755d97fd1f819b84',
    messagingSenderId: '691260257997',
    projectId: 'dcme-app',
    storageBucket: 'dcme-app.appspot.com',
    iosClientId: '691260257997-cge8c614vfohamdnb75t1p63ehi0k6hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.dcmeapp',
  );
}
